name: healthcare_flutter
description: Frontend Flutter - Healthcare Management (Patients, Doctors, Appointments)
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  http: ^1.2.2
  intl: ^0.19.0
  animations: ^2.0.0
  google_fonts: ^6.2.1           # ðŸ§© dÃ¹ng trong Sidebar + UI
  google_generative_ai: ^0.4.3   # âœ… Gemini AI API
  flutter_spinkit: ^5.2.0        # âœ¨ loader animation Ä‘áº¹p khi login/register

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/1.png
