z
spring:
  datasource:
    # Đọc TOÀN BỘ thông tin DB từ Biến Môi trường
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        "[format_sql]": true

springdoc:
  swagger-ui:
    path: /swagger-ui.html

# Đọc JWT secret từ Biến Môi trường
app:
  jwt:
    secret: ${JWT_SECRET}
    expiration-ms: 86400000  # 24h

# Đọc API keys từ Biến Môi trường
ai:
  gemini:
    model: gemini-1.5-flash-latest
    apikey: ${GEMINI_API_KEY}
    baseurl: "https://generativelanguage.googleapis.com/v1beta/models/"


  openai:
    model: gpt-4o-mini
    apikey: ${OPENAI_API_KEY}
    baseurl: "https://api.openai.com/v1"
